version: "3.8"

services:

  postgressql:
    image: postgres
    container_name: postgresa
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123teste"
      POSTGRES_DB: "TCG_MANAGER"
      POSTGRES_USER: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 0s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rbbtmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 0s
    
  api:
    depends_on:
      postgressql:
        condition:  service_healthy
      rabbitmq:
          condition: service_healthy
    container_name: api
    build: .
    command: npm run dev
    ports:
      - "3333:3333"
    environment:

